# Application Secrets

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

stage:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
