source "https://rubygems.org"

gem "pg", "~> 1.0"
gem "puma", "~> 3.11"
gem "rails", "~> 5.1"
gem "rake", "~> 12.3"
gem "slim-rails", "~> 3.1"
gem "webpacker", "~> 3.4"

group :development, :test do
  gem "awesome_print", "~> 1.8"
  gem "bond", "~> 0.5"
  gem "bootsnap", "~> 1.2", require: false
  gem "bundler-audit", "~> 0.6"
  gem "git-cop", "~> 2.2"
  gem "hirb", "~> 0.7"
  gem "pry", "~> 0.10"
  gem "pry-byebug", "~> 3.5"
  gem "reek", "~> 5.0", require: false
  gem "rspec-rails", "~> 3.8"
  gem "rubocop", "~> 0.60", require: false
  gem "wirb", "~> 2.1"
end

group :development do
  gem "listen", "~> 3.1"
  gem "milestoner", "~> 8.2", require: false
  gem "pragmater", "~> 5.2", require: false
  gem "tocer", "~> 7.1", require: false
end

group :test do
  gem "capybara", "~> 3.1"
  gem "climate_control", "~> 0.1"
  gem "codeclimate-test-reporter", "~> 1.0"
  gem "factory_bot_rails", "~> 4.8"
  gem "launchy", "~> 2.4"
  gem "vcr", "~> 4.0"
end
