require_relative "config/application"

begin
  require "git/cop/rake/setup"
  require "reek/rake/task"
  require "rubocop/rake_task"

  Reek::Rake::Task.new
  RuboCop::RakeTask.new
rescue LoadError => error
  puts error.message
end

Rails.application.load_tasks

desc "Run code quality checks"
task code_quality: %i[git_cop reek rubocop]

task(:default).clear
task default: %w[code_quality spec]
